name: daily-devcard

on:
  # Runs when you push to main branch
  push:
    branches: [ "main" ]
  # Runs at 10:00 AM PST daily
  schedule:
    - cron: "0 0 * * *"
  # Allows manual trigger from GitHub
  workflow_dispatch:

jobs:
  devcard:
    runs-on: macos-latest
    timeout-minutes: 15
    
    permissions:
      contents: write
      
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      
      - name: Generate devcard
        uses: dailydotdev/action-devcard@3.0.0
        with:
          user_id: ${{ secrets.laiqrind }}
          commit_message: "chore: update ${README.md}"
